### ISSUE TITLE
Enhancements

### ISSUE THREAD

**Issue by fungl164** [duivvv/fffast#1]
Hi,

Would you consider using BrowserSync alongside webpack?  Perhaps via a plugin like: https://github.com/Va1/browser-sync-webpack-plugin 

Also use separate folders for input/output such as src & dist to separate concerns more easily in the editor / file-browser...

Many thanks.  Awesome work!

Best,

Luis

**Comment by duivvv** [comment]
I'm planning on changing the structure, #7 
will be available in the 2.0.0 release
